on:
  push:
    branches:
      - main

jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt update

      - name: Install Node.js
        run: sudo apt install -y nodejs

      - name: Check Node.js version
        run: node -v

      - name: Install npm package 
        run: sudo apt install -y npm

      - name: Check npm version
        run: npm -v
